apiVersion: v1
kind: Service
metadata:
  name: sparkle-audio
  namespace: sparkle-audio
  labels:
    app.kubernetes.io/name: sparkle-audio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sparkle-audio
  ports:
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
